name: Comment on newly created issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump github context"
        run: echo '${{ toJson(github.event) }}' | jq # Dump the github context
      
      - name: Comment on the issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With Github **Markdown** :sparkles:
            - Issue: ${{ github.event.issue.html_url }}